name: mytodolist
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cool_alert: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  intl: ^0.18.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "images/launcher.png"

flutter:
  uses-material-design: true
  assets:
    - images/
